server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:15433/ead-authuser
    username: matheus-glauber
    password: adminGlaub
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob-non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true

## swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

